// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/upload" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/NotFound.tsx": {
    id: "routes/NotFound";
    page: "/*";
  };
};